config/routes.rb
Droidlandia::Application.routes.draw do
  resources :guests

  resources :hosts

  resources :apk_bins

  mount Resque::Server, :at => "/resque"

  match 'vnc' => 'guests#vnc'

   root :to => 'apk_bins#index'

end

app/models/apk_bin.rb
require 'paperclip'

class ApkBin
  include MongoMapper::Document
  include Paperclip::Glue

  key :intent, String

  has_attached_file :apk, dependent: :destroy,
    :path => ':rails_root/public/system/:class/:id/:style/:basename.:extension',
    :url => '/:class/:id/:apk'
    
  key :apk_file_name, String

  validates :intent, presence: true
  validates :apk_file_name, presence: true

  timestamps!

end

app/models/guest.rb
class Guest
    include MongoMapper::Document

    key :bytes_rcvd, Integer
    key :bytes_sent, Integer
    key :hostname, String
    many :interfaces
    key :os, String
    key :ram, Integer
    key :status, String
    key :vmid, Integer
    key :vnc_port, Integer
end

class Interface
    include MongoMapper::EmbeddedDocument

    key :name, String
    key :ip, String
    key :mac, String
    key :netmask, String
    key :gateway, String
    key :subnet, Integer
end

app/models/host.rb
class Host
    include MongoMapper::Document

    key :hostname, String
    many :interfaces
    key :os, String
    key :release, String
    key :version, String

end

class Interface
    include MongoMapper::EmbeddedDocument

    key :name, String
    key :ip, String
    key :mac, String
    key :netmask, String
    key :broadcast, String
    key :bytes_sent, Integer
    key :bytes_rcvd, Integer
end

app/controllers/apk_bins_controller.rb
class ApkBinsController < ApplicationController
  # GET /apk_bins
  # GET /apk_bins.json
  def index
    @apk_bins = ApkBin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apk_bins }
    end
  end

  # GET /apk_bins/1
  # GET /apk_bins/1.json
  def show
    @apk_bin = ApkBin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apk_bin }
    end
  end

  # GET /apk_bins/new
  # GET /apk_bins/new.json
  def new
    @apk_bin = ApkBin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apk_bin }
    end
  end

  # GET /apk_bins/1/edit
  def edit
    @apk_bin = ApkBin.find(params[:id])
  end

  # POST /apk_bins
  # POST /apk_bins.json
  def create
    @apk_bin = ApkBin.new()
    @apk_bin.apk = params[:file] if params.has_key?(:file)
    @apk_bin.intent = "foobar" #params[:intent] if params.has_key?(:intent)
    @apk_bin.save!

    puts "Saving"

    respond_to do |format|
      if @apk_bin.save
        puts "Putting into queue"
        Resque.enqueue(AdbWorker, @apk_bin.id)
        format.html { redirect_to @apk_bin, notice: 'Apk bin was successfully created.' }
        format.json { render json: @apk_bin, status: :created, location: @apk_bin }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @apk_bin.errors, status: :unprocessable_entity }
        format.js
      end

    end
  end

  # PUT /apk_bins/1
  # PUT /apk_bins/1.json
  def update
    @apk_bin = ApkBin.find(params[:id])

    respond_to do |format|
      if @apk_bin.update_attributes(params[:apk_bin])
        format.html { redirect_to @apk_bin, notice: 'Apk bin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apk_bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apk_bins/1
  # DELETE /apk_bins/1.json
  def destroy
    @apk_bin = ApkBin.find(params[:id])
    @apk_bin.destroy

    respond_to do |format|
      format.html { redirect_to apk_bins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  # GET /guests
  # GET /guests.json
  def index
    #@guests = Guest.all
    @guests = Guest.page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guests }
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest = Guest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/new
  # GET /guests/new.json
  def new
    @guest = Guest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/1/edit
  def edit
    @guest = Guest.find(params[:id])
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(params[:guest])

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render json: @guest, status: :created, location: @guest }
      else
        format.html { render action: "new" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guests/1
  # PUT /guests/1.json
  def update
    @guest = Guest.find(params[:id])

    respond_to do |format|
      if @guest.update_attributes(params[:guest])
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end


  def vnc
    respond_to do |format|
      format.html { 
        render 'vnc_auto.html', :layout => false
      }
    end
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  # GET /hosts
  # GET /hosts.json
  def index
    #@hosts = Host.all
    @hosts = Host.page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hosts }
    end
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
    @host = Host.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @host }
    end
  end

  # GET /hosts/new
  # GET /hosts/new.json
  def new
    @host = Host.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @host }
    end
  end

  # GET /hosts/1/edit
  def edit
    @host = Host.find(params[:id])
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(params[:host])

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render json: @host, status: :created, location: @host }
      else
        format.html { render action: "new" }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hosts/1
  # PUT /hosts/1.json
  def update
    @host = Host.find(params[:id])

    respond_to do |format|
      if @host.update_attributes(params[:host])
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host = Host.find(params[:id])
    @host.destroy

    respond_to do |format|
      format.html { redirect_to hosts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/apk_bins_helper.rb
module ApkBinsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/apk_bins/_form.html.erb
<%= stylesheet_link_tag "plupload/jquery.plupload.queue/css/jquery.plupload.queue" %>
<%= javascript_include_tag "plupload/plupload.full" %>
<%= javascript_include_tag "plupload/jquery.plupload.queue/jquery.plupload.queue" %>
<%= javascript_tag do %>
    <%= render "form.js" %>
<% end %>
<style>
    #apk-drop-zone {
        ddisplay: block;
        text-align: center;
        padding: 1em 0;
        margin: 1em 0;
        color: #CCC;
        border: 2px dashed #C5C5C5;
        height: 200px;
        border-radius: 15px;
        vertical-align: middle;
        line-height: 8em;
        background: url("/assets/android_skateboard_small.gif") center top no-repeat;
        
    }
</style>


<div class="row">
    <div class="span12">
        <form class="form-inline">
            <fieldset>
                <legend>Droidlandia Sweetness</legend>
                <div class="control-group">
                    <div id="apk-container" class="controls">

                        <div id="apk-drop-zone">
                            <h1 style="vertical-align: middle;">Drop APK Here</h1>
                        </div>
                        <div id="upload-progress-ctr" class="progress progress-striped active">
                            <div id="upload-progress" class="bar" style="width: 0%;"></div>
                        </div>
                        <div id="upload-result"></div>

                    </div>
                </div>
                <div class="form-actions">
                    <button id="browse-button" type="submit" class="btn btn-primary">Upload</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<%
=begin %>
<% form_for(@apk_bin, :html => {:multipart => true}) do |f| %>
  <% if @apk_bin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apk_bin.errors.count, "error") %> prohibited this apk_bin from being saved:</h2>

      <ul>
      <% @apk_bin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :intent %><br />
    <%= f.text_field :intent %>
  </div>
  <div class="field">
    <%= f.label :apk %><br />
    <%= f.file_field :apk %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%
=end %>

app/views/apk_bins/_form.js.erb
<% session_key_name = Rails.application.config.session_options[:key] %>
$(function() {
   var uploader = new plupload.Uploader({
    runtimes: 'html5,flash,silverlight',
    url: '<%= apk_bins_path %>',
    max_file_size: '50mb',
    browse_button: "browse-button",
    flash_swf_url: "/javascripts/plupload/plupload.flash.swf",  
    silverlight_xap_url: "/javascripts/plupload/plupload.silverlight.xap",
    autostart: true,
    multipart: true,
    container: "apk-container",
    drop_element: "apk-drop-zone",
    unique_names : true,
    multipart_params: {
      '_http_accept': 'application/javascript',
      'authenticity_token' : '<%= form_authenticity_token %>',
      '<%= session_key_name %>' : encodeURIComponent('<%= u cookies[session_key_name] %>'),
      'intent': $('#apk_bin_intent').val()
    },
    filters: [
      {title: "APK", extensions: "apk"}
    ]
  });


    var dropzone = $("#apk-drop-zone");
    var $body = $("body");
    $body.bind("dragenter", function(e){ 
        e.stopPropagation();
        e.preventDefault();
    });

    $body.bind("dragleave", function(e){ 
    });
    
    $body.bind("dragover", function(e){
        e.stopPropagation();
        e.preventDefault();
    });

    $body.bind("drop", function(e){
        e.stopPropagation();
        e.preventDefault();
    });

    dropzone.bind("dragenter", function(e){
        e.stopPropagation();
        e.preventDefault();
    });
    dropzone.bind("dragleave", function(e){  });
    dropzone.bind("dragover", function(e){
        e.stopPropagation();
        e.preventDefault();
    });

    $("#upload-progress-ctr").hide();
    $("#upload-result").hide();
    uploader.bind('Init', function(up, params) {
        $("#browse-button").hide();
    });
    uploader.init();
    
    uploader.bind('FilesAdded', function(up, files) {
        $("#apk-drop-zone").hide();
        uploader.start();
    });

    uploader.bind('Error', function(up, err) {
        up.refresh();
    });

    uploader.bind('BeforeUpload', function(up, file, info) {
        $("#upload-progress-ctr").show();
        up.settings.multipart_params.intent = $('#apk_bin_intent').val()
    });
    
    uploader.bind('UploadProgress', function(up, file) {
        $('#upload-progress').css('width',file.percent + '%');
    });

    uploader.bind('FileUploaded', function(up, file) {
        $('#upload-progress-ctr').hide();
        $('#upload-result').html("<h1>APK Upload Successful</h1>");
        $('#upload-result').fadeIn('slow'); 
    });
   
});

app/views/apk_bins/create.js.erb
$('#apk_bin_container').html('Upload Successful');

app/views/apk_bins/edit.html.erb
<h1>Editing apk_bin</h1>

<%= render 'form' %>

<%= link_to 'Show', @apk_bin %> |
<%= link_to 'Back', apk_bins_path %>

app/views/apk_bins/index.html.erb
<h1>Listing apk_bins</h1>

<table>
  <tr>
    <th>APK Bin ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apk_bins.each do |apk_bin| %>
  <tr>
    <td><%= apk_bin.apk_file_name %></td>
    <td><%= link_to 'Show', apk_bin %></td>
    <td><%= link_to 'Edit', edit_apk_bin_path(apk_bin) %></td>
    <td><%= link_to 'Destroy', apk_bin, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Apk bin', new_apk_bin_path %>

app/views/apk_bins/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', apk_bins_path %>

app/views/apk_bins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Intent:</b>
  <%= @apk_bin.intent %>
</p>


<%= link_to 'Edit', edit_apk_bin_path(@apk_bin) %> |
<%= link_to 'Back', apk_bins_path %>

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<h1>Listing guests</h1>

<br>

  <table class="table table-striped table-bordered">
      <thead>
          <tr>
            <th>Hostname</th>
            <th>Status</th>
          </tr>
      </thead>
      <tbody>
        <% @guests.each do |guest| %>
          <tr>
            <td><%= link_to guest.hostname, guest %></td>
            <td><%= guest.status %></td>
          </tr>
        <% end %>
      </tbody>
  </table>

</br>


<%= link_to 'New Guest', new_guest_path %>

<%= paginate @guests %>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<%= javascript_include_tag 'open_vnc_window' %>

<p id="notice"><%= notice %></p>

<h1><%= @guest.hostname %></h1>

<br>

  <table class="table table-striped table-bordered">
      <h3>Vitals</h3>
      <thead>
          <tr>
            <th>Status</th>
            <th>Bytes Received</th>
            <th>Bytes Sent</th>
            <th>OS</th>
            <th>RAM</th>
            <th>VM ID</th>
            <th>VNC Port</th>
          </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @guest.status %></td>
            <td><%= @guest.bytes_rcvd %></td>
            <td><%= @guest.bytes_sent %></td>
            <td><%= @guest.os %></td>
            <td><%= @guest.ram %></td>
            <td><%= @guest.vmid %></td>

            <!-- TODO: don't hardcode the server ip -->

            <script>
              var novnc_host="134.252.32.73"
              var novnc_port="6080"

              var novnc_server_url = "http://" + novnc_host + ":" + novnc_port + "/vnc_auto.html?host=" + novnc_host + "&remoteprt="
              var remote_port = <%= @guest.vnc_port %>

              var vnc_path = novnc_server_url + remote_port
            </script>
            <td><button type="button" class="btn btn-primary" id="open_vnc_window_button"><%= @guest.vnc_port %></button></td>
          </tr>
      </tbody>
  </table>

  <table class="table table-striped table-bordered">
      <h3>Interfaces</h3>
      <thead>
          <tr>
            <th>Name</th>
            <th>IP</th>
            <th>MAC</th>
            <th>Netmask</th>
            <th>Gateway</th>
            <th>Subnet</th>
          </tr>
      </thead>
      <tbody>
        <% @guest.interfaces.each do |interface| %>
          <tr>
            <td><%= interface.name %></td>
            <td><%= interface.ip %></td>
            <td><%= interface.mac %></td>
            <td><%= interface.netmask %></td>
            <td><%= interface.gateway %></td>
            <td><%= interface.subnet %></td>
          </tr>
        <% end %>
      </tbody>
  </table>

</br>


<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<h1>Listing hosts</h1>

<br>

  <table class="table table-striped table-bordered">
      <thead>
          <tr>
            <th>Hostname</th>
            <th>OS</th>
          </tr>
      </thead>
      <tbody>
        <% @hosts.each do |host| %>
          <tr>
            <td><%= link_to host.hostname, host %></td>
            <td><%= host.os %></td>
          </tr>
        <% end %>
      </tbody>
  </table>

</br>

<%= link_to 'New Host', new_host_path %>

<%= paginate @hosts %>

app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @host.hostname %></h1>

<br>

  <table class="table table-striped table-bordered">
      <h3>Vitals</h3>
      <thead>
          <tr>
            <th>OS</th>
            <th>Release</th>
            <th>Version</th>
          </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @host.os %></td>
            <td><%= @host.release %></td>
            <td><%= @host.version %></td>
          </tr>
      </tbody>
  </table>

  <table class="table table-striped table-bordered">
      <h3>Interfaces</h3>
      <thead>
          <tr>
            <th>Name</th>
            <th>IP</th>
            <th>MAC</th>
            <th>Netmask</th>
            <th>Broadcast</th>
            <th>Bytes Sent</th>
            <th>Bytes Received</th>
          </tr>
      </thead>
      <tbody>
        <% @host.interfaces.each do |interface| %>
          <tr>
            <td><%= interface.name %></td>
            <td><%= interface.ip %></td>
            <td><%= interface.mac %></td>
            <td><%= interface.netmask %></td>
            <td><%= interface.broadcast %></td>
            <td><%= interface.bytes_sent %></td>
            <td><%= interface.bytes_rcvd %></td>
          </tr>
        <% end %>
      </tbody>
  </table>

</br>


<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Droidlandia</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "bootstrap/bootstrap.min", :media => "all" %>
    <%= stylesheet_link_tag "bootstrap/bootstrap-responsive.min", :media => "all" %>
    <%= javascript_include_tag "bootstrap/bootstrap.min" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">droidlandia</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="<%= 'active' if params[:controller] == 'apk_bins' %>"><a href="/apk_bins">APK Bins</a></li>
              <li class="<%= 'active' if params[:controller] == 'hosts' %>"><a href="/hosts">Hosts</a></li>
              <li class="<%= 'active' if params[:controller] == 'guests' %>"><a href="/guests">Guests</a></li>
              <li class="<%= 'active' if params[:controller] == 'resque' %>"><a href="/resque">Resque</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>